version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "love"
      POSTGRES_DB: golang
    ports:
      - '5432:5432'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'

  memcached:
    image: 'memcached:latest'
    ports:
      - '11211:11211'

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq'
    ports:
      - '5672:5672'

  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=coursera
    ports:
      - '27017-27019:27017-27019'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  tarantool:
    build: ../10_tarantool_simple
    restart: always
    ports:
      - 3301:3301
